auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Li Qingyao
url: http://life.liqingyao.com
feed: /atom.xml
author_info: <a href="http://liqingyao.com/">LiQingyao</a>
