# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Li Qingyao
tagline:          'Annie'
description:      'My name'
url:              http://life.liqingyao.com
baseurl:          /

author:
name:             'Mark Otto'
url:              https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0
github:           https://github.com/liqingyao
repo:             https://github.com/liqingyao

# PAGINATION
#markdown:         rdiscount
#gems:             [jekyll-paginate]
#gems:             [jekyll-gist]
#paginate:         5
#paginate_path:    "page:num"
