auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: liqingyao.com
url: http://code.liqingyao.com
feed: /atom.xml
author_info: <a href="http://liqingyao.com/">LiQingyao</a>
