# Site settings
title: Li Qingyao
email: qingyao.li@yahoo.com
description: Hello World
baseurl: ""
url: "http://code.liqingyao.com"

author:
  name     : 'Li Qingyao'
  email    : qingyao.li@yahoo.com
  url      : http://code.liqingyao.com

github: https://github.com/liqingyao
linkedin: https://www.linkedin.com/in/liqingyao
weibo: http://weibo.com/leeleeannie
disqus_shortname: "codeliqingyao"
google_analytics: UA-52446115-1

paginate: 9
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
